[mypy]
python_version = 3.12
strict = True
warn_unused_ignores = True
warn_return_any = True
warn_redundant_casts = True
ignore_missing_imports = False
disallow_untyped_decorators = False

[mypy-duckdb.*]
ignore_missing_imports = True

[mypy-supabase.*]
ignore_missing_imports = True

[mypy-selectolax.*]
ignore_missing_imports = True

[mypy-xlsxwriter.*]
ignore_missing_imports = True

[mypy-yaml]
ignore_missing_imports = True
